# Generated by Django 6.0.4 on 2026-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
